- hosts: all
  become: yes
  tasks:
  - name : Install unzip package
    apt: name="{{package}}" state=present update_cache=true
    loop: ["{{eins}}", "{{zwei}}", "{{drei}}", "{{vier}}", "{{fuenf}}"]
